services:
  - type: web
    name: rice-disease-agent
    runtime: python
    plan: free
    buildCommand: uv sync
    startCommand: uv run python -m app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        fromService:
          type: web
          name: rice-disease-agent
          property: port
    healthCheckPath: /health